src/Entity/Klant.php
<?php

namespace App\Entity;

use App\Repository\KlantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KlantRepository::class)
 */

class Klant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Naam;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Straat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Huisnummer;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Woonplaats;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Postcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Telefoonnummer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Email;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="Klant")
     */
    private $invoices;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->Naam;
    }

    public function setNaam(string $Naam): self
    {
        $this->Naam = $Naam;

        return $this;
    }

    public function getStraat(): ?string
    {
        return $this->Straat;
    }

    public function setStraat(string $Straat): self
    {
        $this->Straat = $Straat;

        return $this;
    }

    public function getHuisnummer(): ?string
    {
        return $this->Huisnummer;
    }

    public function setHuisnummer(string $Huisnummer): self
    {
        $this->Huisnummer = $Huisnummer;

        return $this;
    }

    public function getWoonplaats(): ?string
    {
        return $this->Woonplaats;
    }

    public function setWoonplaats(string $Woonplaats): self
    {
        $this->Woonplaats = $Woonplaats;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->Postcode;
    }

    public function setPostcode(string $Postcode): self
    {
        $this->Postcode = $Postcode;

        return $this;
    }

    public function getTelefoonnummer(): ?string
    {
        return $this->Telefoonnummer;
    }

    public function setTelefoonnummer(?string $Telefoonnummer): self
    {
        $this->Telefoonnummer = $Telefoonnummer;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setKlant($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getKlant() === $this) {
                $invoice->setKlant(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>

        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}

        {% block head_css %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        {% endblock %}

        {% block head_js %}
            <script src='//cdn.jsdelivr.net/npm/sweetalert2@11'></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/createKlant.html.twig
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<link rel="stylesheet" href="build/app.css">
		<title>Autohuys Rhenen Dashboard</title>
		<link rel="icon" type="image/png" href="/images/favicon.png"/>
	</head>
	<body>

		{% if is_granted('IS_AUTHENTICATED_FULLY') %}
			<div class="main">
				<div class="sidenav">
					<img class="logo" src="images/logo.png"/>
					<div class="menu">
						<a href="/home">Overzicht</a>
						<a href="/maak-factuur">Factuur maken</a>
						<a href="/overzicht-facturen">Facturen overzicht</a>
						<a href="/maak-klant">Klant toevoegen</a>
					</div>

					<div class="profile">
						<div class="photo">
							<img class="profilepicture" src="images/ProfielfotoHarry.png">
						</div>
						<div class="info">
							<h5>Harry Vos</h5>
							<p>Administrator</p>
						</div>
					</div>
				</div>

				<div class="content">
					<div class="voorraad">
						{{ form_start(form) }}

						<div class="my-custom-class-for-errors">
							{{ form_errors(form) }}
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.Naam) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.Telefoonnummer) }}
							</div>
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.Straat) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.Huisnummer) }}
							</div>
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.Woonplaats) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.Postcode) }}
							</div>
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.Email) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.Save) }}
							</div>
						</div>

						{{ form_end(form) }}
					</div>
				</div>
			</div>
		{% else %}
			<script>
				window.location.href = '/login'
			</script>
		{% endif %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	</body>
</html>

templates/dashboard.html.twig
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

		{{ encore_entry_link_tags('app') }}

		<title>Autohuys Rhenen Dashboard</title>
		<link rel="icon" type="image/png" href="../images/favicon.png"/>
	</head>
	<body>

		{% if is_granted('IS_AUTHENTICATED_FULLY') %}
			<div class="main">
				<div class="sidenav">
					<img class="logo" src="images/logo.png"/>
					<div class="menu">
						<a href="/home">Overzicht</a>
						<a href="/maak-factuur">Factuur maken</a>
						<a href="/maak-klant">Klant toevoegen</a>
						{# <a href="showroom.html.twig">Showroom map</a>
						                <a href="detail.html.twig">Detailing lijst</a>
						                <a href="werknemers.html.twig">Werknemers</a> #}
					</div>

					<div class="profile">
						<div class="photo">
							<img class="profilepicture" src="images/ProfielfotoHarry.png">
						</div>
						<div class="info">
							<h5>Harry Vos</h5>
							<p>{{ app.user.email }}</p>
						</div>
					</div>
				</div>

				<div class="content">
					<div class="overview-area">
						<div class="stock">
							<h3>Auto's op Voorraad</h3>
							<h1>{{ voorraad }}</h1>
						</div>
						<div class="review">
							<h3>Klanttevredenheid</h3>
							<h1>9.8</h1>
						</div>
						<div class="detail">
							<h3>Auto's op detail lijst</h3>
							<h1>7</h1>
						</div>
					</div>
					<div class="header-todo">
						<h2>Todo</h2>
					</div>
					<div class="todo-list">
						<div class="morning">
							<h2>9:00 - 12:00</h2>
							<p>Foto's maken</p>
						</div>
						<div class="lunchtime">
							<h2>12:00 - 13:00</h2>
							<p>Lunchen</p>
						</div>
						<div class="customer">
							<h2>13:00 - 15:00</h2>
							<p>Klanten helpen</p>
						</div>
					</div>
				</div>
			</div>
		{% else %}
			<script>
				window.location.href = '/login'
			</script>
		{% endif %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	</body>
</html>

templates/form.html.twig
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<link rel="stylesheet" href="build/app.css">
		<title>Autohuys Rhenen Dashboard</title>
		<link rel="icon" type="image/png" href="/images/favicon.png"/>
	</head>
	<body>

		{% if is_granted('IS_AUTHENTICATED_FULLY') %}
			<div class="main">
				<div class="sidenav">
					<img class="logo" src="images/logo.png"/>
					<div class="menu">
						<a href="/home">Overzicht</a>
						<a href="/maak-factuur">Factuur maken</a>
						<a href="/overzicht-facturen">Facturen overzicht</a>
						<a href="/maak-klant">Klant toevoegen</a>
					</div>

					<div class="profile">
						<div class="photo">
							<img class="profilepicture" src="images/ProfielfotoHarry.png">
						</div>
						<div class="info">
							<h5>Harry Vos</h5>
							<p>Administrator</p>
						</div>
					</div>
				</div>

				<div class="content">
					<div class="voorraad">
						{{ form_start(form) }}

						<div class="my-custom-class-for-errors">
							{{ form_errors(form) }}
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.invoicenumber) }}
							</div>
							<div class="col">
								{{ form_row(form.invoicedate, { value : "now"|date("m/d/Y")}) }}
							</div>
							<div class="col">
								{{ form_row(form.Klant) }}
							</div>
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.license) }}
							</div>
							<div class="col">
								{{ form_row(form.Kilometerstand) }}
							</div>
							<div class="col">
								{{ form_row(form.margebtw) }}
							</div>
							<div class="col">
								{{ form_row(form.Prijs) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.meldcode) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.Garantie) }}
							</div>
						</div>

						<div class="row">
							<div class="col">
								{{ form_row(form.Inruilprijs) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.subtotaal) }}
							</div>
							<div class="col" id="some-custom-id">
								{{ form_row(form.totaal) }}
							</div>
						</div>

						{{ form_end(form) }}
					</div>
				</div>
			</div>
		{% else %}
			<script>
				window.location.href = '/login'
			</script>
		{% endif %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	</body>
</html>

templates/overzichtFacturen.html.twig
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<link rel="stylesheet" href="build/app.css">
		<title>Autohuys Rhenen Dashboard</title>
		<link rel="icon" type="image/png" href="/images/favicon.png"/>
	</head>
	<body>

		{% if is_granted('IS_AUTHENTICATED_FULLY') %}
			<div class="main">
				<div class="sidenav">
					<img class="logo" src="images/logo.png"/>
					<div class="menu">
						<a href="/home">Overzicht</a>
						<a href="/maak-factuur">Factuur maken</a>
						<a href="/overzicht-facturen">Facturen overzicht</a>
						<a href="/maak-klant">Klant toevoegen</a>
					</div>

					<div class="profile">
						<div class="photo">
							<img class="profilepicture" src="images/ProfielfotoHarry.png">
						</div>
						<div class="info">
							<h5>Harry Vos</h5>
							<p>Administrator</p>
						</div>
					</div>
				</div>

				<div class="content">
					{% for invoice in invoices %}
						<li>{{ invoice.invoicenumber }}</li>
					{% endfor %}
				</div>
			</div>
		{% else %}
			<script>
				window.location.href = '/login'
			</script>
		{% endif %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	</body>
</html>